wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1659767579
    t:
      1:
      - 1
      - 5
      - 41
      2:
      - 1
      - 5
      - 41
      3:
      - 1
      - 2
      - 16
      4: 3.9.7
      5: 0.12.11
      8:
      - 5
    visualize:
      test/confusion_matrix:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: test/confusion_matrix_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      train/confusion_matrix:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: train/confusion_matrix_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
adjacency_builder:
  desc: null
  value: cos_sim
batch_size:
  desc: null
  value: 32
builder_parameter:
  desc: null
  value: 0.7
conv_parameters:
  desc: null
  value:
    agg: mean
    num_heads: 4
    residual: true
conv_type:
  desc: null
  value: gcn
criterion:
  desc: null
  value: cross_entropy
device:
  desc: null
  value: cuda:3
early_stopping_tolerance:
  desc: null
  value: 5
epochs:
  desc: null
  value: 2
hidden_dim:
  desc: null
  value: 512
learning_rate:
  desc: null
  value: 0.0003
loss_lambda:
  desc: null
  value: 1
lr_decay_gamma:
  desc: null
  value: 1
lr_decay_steps:
  desc: null
  value: 15
num_classes:
  desc: null
  value: 7
num_hidden:
  desc: null
  value: 2
optimizer:
  desc: null
  value: adam
resize:
  desc: null
  value: 224
use_augmentation:
  desc: null
  value: true
use_both_heads:
  desc: null
  value: false
use_scheduler:
  desc: null
  value: true
